### PR TITLE
add to readme that tailwind.config.js is required

### LINKED ISSUE #74: Suggestion: add to README.md that you need tailwind.config.js for plugin to work
Thanks for the awesome plugin! ⚡️

The `npx tailwind init` is optional if you read the Tailwind CSS docs. It is a bit confusing if you skip that step, install the Tailwind CSS IntelliSense plugin, and autocomplete does not work. 

In other words, it took me some time to figure this out. 😅 It would be great to mention this somewhere in the docs, so that other people would not waste time on this.

### PR DESCRIPTION
**Pull request by ledenis**
fix #74

### CODE REVIEW

**Comment by surjithctly** [comment]
Should also mention that Node & NPM also needed. because just copying the config file won't make it work in a normal folder.

**Comment by ledenis** [comment]
@surjithctly you're right, thanks, updated

**Comment by surjithctly** [comment]
@bradlc If everything's fine here, could you merge this. it would really help newbies like me :)

**Comment by bradlc** [comment]
Thanks @ledenis. Please could you move the new section above the `Features` section? Then I'll get this merged

**Comment by ledenis** [comment]
@bradlc is it OK ? :)

**Comment by bodazhao** [comment]
Would be great to have this merged so newbies like me won't be spending 30 mins wondering why the extension isn't working.

Also, the [required config file](https://github.com/bradlc/vscode-tailwindcss/blob/next/src/class-names/index.js#L35) condition is: 

```
**/{tailwind,tailwind.config,tailwind-config,.tailwindrc}.js
```

It doesn't have to be `tailwind.config.js`

**Pull request merged**
